/* GENERATED by tools/tts/generate_clips.py — do not edit by hand. */
window.Glyphs = window.Glyphs || {};
window.Glyphs.audio = window.Glyphs.audio || {};
window.Glyphs.audio.manifest = {
  primary: "callirrhoe",
  voices: ["callirrhoe", "sulafat", "aoede"],
  ext: "wav",
  words: ["the", "and", "run", "mom", "dad", "see", "go", "like", "you", "me", "cat", "dog", "sun", "moon", "tree", "star", "apple", "fish", "bird", "rain"],
  bakeoffWords: ["cat", "sun", "apple", "the", "run"]
};
